import * as React from 'react';
import Head from 'next/head'

import Container from '@mui/material/Container';

import ResponsiveHeader from '../Header'

const MainWrapper = (props: any) => {
  return (
    <>
      <Head>
        <title>React To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveHeader menus={props.menus}/>
      <Container maxWidth={props.maxWidth ? props.maxWidth : "md"} sx={{mt: 20}}>
        {props.children}
      </Container>
    </>
  )
}

export default MainWrapper
