import * as React from 'react';
import Head from 'next/head'
import Container from '@mui/material/Container';
import ResponsiveHeader from '../Header'
import MenuType from '../../Types/MenuType';

type MainWrapperProps = {menus?: Array<MenuType>, maxWidth?: any, children: any};

const MainWrapper = ({menus = [], maxWidth, children}: MainWrapperProps) => {
  return (
    <>
      <Head>
        <title>React To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveHeader menus={menus}/>
      <Container maxWidth={maxWidth || "md"} sx={{mt: 20}}>
        {children}
      </Container>
    </>
  )
}

export default MainWrapper
